version: '3'

services:
  mosquitto-broker:
    container_name: mosquitto-broker
    build:
      context: mosquitto
      dockerfile: Dockerfile
      args:
        - PASSWORD_PATH=/config/password.txt
    env_file:
      - "./.env"
    volumes:
      - type: bind
        source: ./cert/generated
        target: /mosquitto/certs/
        read_only: false
      - type: bind
        source: ./config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
        read_only: false
      - type: bind
        source: ./log
        target: /mosquitto/log/
        read_only: false
      - type: volume
        source: data_network
        target: /mosquitto/data/
    ports:
      - "8883:8883"
      - "9001:9001"
    networks:
      - iot_networks
    depends_on:
      ssl:
        condition: service_completed_successfully

  # mosquitto-pub:
  #   container_name: mosquitto-pub
  #   image: eclipse-mosquitto:2.0
  #   volumes:
  #     - type: bind
  #       source: ./cert/mosquitto
  #       target: /mosquitto/certs/
  #       read_only: false
  #   depends_on:
  #     - mosquitto-broker
  #     - mosquitto-sub
  #   networks:
  #     - iot_networks

  mosquitto-sub:
    container_name: mosquitto-sub
    image: eclipse-mosquitto:2.0
    volumes:
      - type: bind
        source: ./cert/generated
        target: /mosquitto/certs/
        read_only: false
    command: sh -c "mosquitto_sub -h mosquitto-broker -t topics/iot -u admin -P admin --cert /mosquitto/certs/ca.crt --key /mosquitto/certs/client.key --tls-version tlsv1.2"
    depends_on:
      - mosquitto-broker
    networks:
      - iot_networks

  ssl:
    container_name: ssl
    build:
      context: cert
      dockerfile: Dockerfile
    networks:
      - iot_networks
    volumes:
      - type: bind
        source: ./cert/generated
        target: /cert/mosquitto/generated
        read_only: false

networks:
  iot_networks:
    driver: bridge
volumes:
  data_network:
    name: "iot_data_network"

