version: '3'

services:
  mosquitto-broker:
    container_name: mosquitto-broker
    hostname: mosquitto-broker
    build:
      context: .
      dockerfile: mosquitto-broker.Dockerfile
      args:
        - PASSWORD_PATH=/mosquitto/config/password.txt
    env_file:
      - "./.env"
    volumes:
      - type: bind
        source: ./config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
        read_only: false
      - type: bind
        source: ./log
        target: /mosquitto/log/
        read_only: false
      - type: volume
        source: data_network
        target: /mosquitto/data/
    ports:
      - "8883:8883"
      - "9001:9001"
    networks:
      - iot_networks
    profiles:
      - mosquitto

  mosquitto-pub:
    container_name: mosquitto-pub
    hostname: mosquitto-pub
    image: eclipse-mosquitto:2.0
    volumes:
      - type: bind
        source: ./cert/generated
        target: /mosquitto/certs/
        read_only: false
    depends_on:
      - mosquitto-broker
      - mosquitto-sub
    networks:
      - iot_networks
    profiles:
      - mosquitto

  mosquitto-sub:
    container_name: mosquitto-sub
    hostname: mosquitto-sub
    image: eclipse-mosquitto:2.0
    volumes:
      - type: bind
        source: ./cert/generated
        target: /mosquitto/certs/
        read_only: false
    command: sh -c "mosquitto_sub -h mosquitto-broker -t topics/# -u admin -P admin --cafile /mosquitto/certs/ca.crt --tls-version tlsv1.2"
    depends_on:
      - mosquitto-broker
    networks:
      - iot_networks
    profiles:
      - mosquitto
      - mosquitto-broker

  ssl:
    container_name: ssl
    build:
      context: cert
      dockerfile: cert.Dockerfile
    networks:
      - iot_networks
    volumes:
      - type: bind
        source: ./cert/generated
        target: /cert/generated
        read_only: false
        bind:
          create_host_path: true
    profiles:
      - ssl

networks:
  iot_networks:
    driver: bridge
volumes:
  data_network:
    name: "iot_data_network"

